updated tests script

diff --git a/projects/project_2/stage1/test b/projects/project_2/stage1/test
--- a/projects/project_2/stage1/test
+++ b/projects/project_2/stage1/test
@@ -2,6 +2,29 @@
 
 # Adapted from André Daniel Gomes's Test script
 
+# usage|help|info: ./test -q <server timeout> -u <client timeout> -f <server fifo>
+
+# default values
+serverTime=10
+clientTime=15
+fifoname='fifo.server'
+
+while getopts ":q:u:f:" opt; do
+  case $opt in
+    q) serverTime=$OPTARG;;
+    u) clientTime=$OPTARG;;
+    f) fifoname=$OPTARG;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
 echo "╔══════════════════════════╗"
 echo "║       RUNNING TESTS      ║"
 echo "╚══════════════════════════╝"
@@ -14,13 +37,13 @@ make &> /dev/null
 
 if [ $? -eq 0 ] ; then
   mkdir logs
-  echo "Setting server timeout to 20sec"
-  echo "Setting client timeout to 15sec"
+  echo "Setting server timeout to "$serverTime"sec"
+  echo "Setting client timeout to "$clientTime"sec"
   echo "SERVER/CLIENT RUNNING ..."
 
-  ./Q1 -t 15 server.fifo > logs/q1.log 2> logs/q1.err &  # Un <-t nsecs> fifoname
+  ./Q1 -t $serverTime "$fifoname" > logs/q1.log 2> logs/q1.err &  # Un <-t nsecs> fifoname
   P1=$!
-  ./U1 -t 20 server.fifo > logs/u1.log 2> logs/u1.err &   # Qn <-t nsecs> [-l nplaces] [-n nthreads] fifoname
+  ./U1 -t $clientTime "$fifoname" > logs/u1.log 2> logs/u1.err &   # Qn <-t nsecs> [-l nplaces] [-n nthreads] fifoname
   P2=$!
   wait $P1 $P2
   echo "END OF SERVER/CLIENT"
@@ -53,15 +76,10 @@ if [ $? -eq 0 ] ; then
   echo "Failed requests: $nFAILD"
 
   cd ..
+
+  # comment this line if you wish to keep the log files (debugging purposes)
   rm -rf logs
   make clean
 else
   echo "MAKE ERROR";
 fi
-
-# make clean
-# Flags Possiveis:
-# -t nsecs      - nº (aproximado) de segundos que o programa deve funcionar
-# fifoname      - nome do canal público (FIFO) a criar pelo servidor para atendimento de pedidos
-# -l nplaces    - lotação do Quarto de Banho
-# -n nthreads   - nº (máximo) de threads a atender pedidos
